### ISSUE TITLE
CSS and HTML LSPs crash kak-lsp when formatting, autocomplete does not work, errors aren't displayed

### ISSUE THREAD

**Issue by Release-Candidate** [kakoune-lsp/kakoune-lsp#798]
The LSPs `vscode-html-language-server` and `vscode-css-language-server` crash when calling a formatting command.

Minimal config:

```text
hook -group lsp-filetype-html global BufSetOption filetype=html %{ 
   set-option buffer lsp_servers %{
        [vscode-html-language-server]
        root_globs = ["package.json", ".git", ".hg"] 
        args = ["--stdio"] 
        settings_section = "_" 
        [vscode-html-language-server.settings._] 
        handledSchemas = ["file"]
        provideFormatter = true 
       } 
}
```

Debug log:

```text
LSP: DEBG TextEdit { range: Range { start: Position { line: 156, character: 0 }, end: Position { line: 156, character: 0 } }, new_text: "                <p>\n                    It's time for me to use a testing framework for Common Lisp, so I\n                    took a look at the available options.\n                </p>\n                <footer>Posted: June 30, 2024</footer>\n            </article>\n        </div>\n" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 158, character: 0 }, end: Position { line: 158, character: 0 } }, new_text: "        <script>\n" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 158, character: 0 }, end: Position { line: 158, character: 0 } }, new_text: "            document.addEventListener(\"readystatechange\", function (event) {\n" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 158, character: 0 }, end: Position { line: 158, character: 0 } }, new_text: "                if (document.readyState == \"complete\") {\n" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 158, character: 0 }, end: Position { line: 158, character: 0 } }, new_text: "                    const cookies = document.cookie;\n                    const theme = cookies\n" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 158, character: 0 }, end: Position { line: 158, character: 0 } }, new_text: "                        .split(\"; \")\n                        .find(function (cookie) {\n                            return cookie.startsWith(\"theme=\");\n                        })\n" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 158, character: 0 }, end: Position { line: 158, character: 0 } }, new_text: "                        ?.split(\"=\")[1];\n                    if (theme != null) {\n                        changeTheme(theme);\n                    } else {\n                        const useDark = window?.matchMedia(\n                            \"(prefers-color-scheme: dark)\",\n                        ).matches;\n                        if (useDark) {\n                            changeTheme(\"dark\");\n" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 158, character: 0 }, end: Position { line: 158, character: 0 } }, new_text: "                        }\n                    }\n                }\n            });\n            function changeTheme(id, changeCookie) {\n                if (changeCookie === \"changeCookie\") {\n                    document.cookie = `theme=${id}; SameSite=Strict; Path=/; max-age=31536000`;\n                }\n                const body_els = document.getElementsByTagName(\"body\");\n                body_els[0].className = id;\n                document.getElementById(\"themeCSS\").href = `${id}.css`;\n                const btn_class = id + \"Button\";\n                const btn_els = document.getElementsByClassName(btn_class);\n                for (let idx = 0; idx < btn_els.length; idx++) {\n                    btn_els[idx].setAttribute(\"aria-pressed\", \"true\");\n                }\n                const other_class = id == \"dark\" ? \"lightButton\" : \"darkButton\";\n                const obtn_els = document.getElementsByClassName(other_class);\n" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 158, character: 0 }, end: Position { line: 167, character: 0 } }, new_text: "" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 167, character: 0 }, end: Position { line: 167, character: 0 } }, new_text: "                for (let idx = 0; idx < obtn_els.length; idx++) {\n                    obtn_els[idx].setAttribute(\"aria-pressed\", \"false\");\n                }\n" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 167, character: 0 }, end: Position { line: 169, character: 0 } }, new_text: "" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 169, character: 0 }, end: Position { line: 173, character: 0 } }, new_text: "" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 173, character: 0 }, end: Position { line: 176, character: 0 } }, new_text: "" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 176, character: 0 }, end: Position { line: 177, character: 0 } }, new_text: "" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 178, character: 0 }, end: Position { line: 179, character: 0 } }, new_text: "" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 179, character: 0 }, end: Position { line: 183, character: 0 } }, new_text: "" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 183, character: 0 }, end: Position { line: 191, character: 0 } }, new_text: "" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 191, character: 0 }, end: Position { line: 200, character: 0 } }, new_text: "" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 200, character: 0 }, end: Position { line: 200, character: 0 } }, new_text: "        </script>\n        <a href=\"sitemap.html\" id=\"siteMap\">Site Map</a>\n        <a href=\"index.html\" id=\"allPosts\">All Posts</a>\n        <a href=\"rss.xml\" id=\"rssLink\">RSS</a>\n        <div aria-labelledby=\"ThemeLabelFooter\" role=\"group\" id=\"ThemeSwitcherFooter\">\n" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 200, character: 0 }, end: Position { line: 204, character: 0 } }, new_text: "" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 204, character: 0 }, end: Position { line: 204, character: 0 } }, new_text: "            <span id=\"ThemeLabelFooter\">Theme</span>:\n            <span id=\"ThemeButtonsFooter\">\n                <button type=\"button\" data-name=\"Light\" aria-pressed=\"true\" id=\"LightThemeFooter\"\n                    aria-labelledby=\"LightThemeFooter ThemeLabelFooter\" onclick=\"changeTheme('light', 'changeCookie');\"\n                    class=\"lightButton\">\n                    Light\n                </button>\n                <button type=\"button\" data-name=\"Dark\" aria-pressed=\"false\" id=\"DarkThemeFooter\"\n                    aria-labelledby=\"DarkThemeFooter ThemeLabelFooter\" onclick=\"changeTheme('dark', 'changeCookie');\"\n                    class=\"darkButton\">\n                    Dark\n                </button>\n            </span>\n        </div>\n        <p id=\"copyRight\">\n            © Roland Csaszar, all of my articles are licensed under the\n            <a href=\"https://creativecommons.org/licenses/by-sa/4.0/\">CC BY-SA 4.0</a>\n        </p>\n" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 204, character: 0 }, end: Position { line: 239, character: 0 } }, new_text: "" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 240, character: 0 }, end: Position { line: 241, character: 0 } }, new_text: "" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 241, character: 0 }, end: Position { line: 242, character: 0 } }, new_text: "" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 242, character: 0 }, end: Position { line: 242, character: 0 } }, new_text: "" }
LSP: DEBG TextEdit { range: Range { start: Position { line: 243, character: 0 }, end: Position { line: 243, character: 0 } }, new_text: "</body>\n\n</html>" }
LSP: ERRO kak-lsp crashed, please report a bug. Find more details in the *debug* buffer.
panicked at src/text_edit.rs:336:13:
assertion failed: start == last.range.end
disabled backtrace
LSP: kak-lsp crashed, please report a bug. Find more details in the *debug* buffer.
panicked at src/text_edit.rs:336:13:
assertion failed: start == last.range.end
disabled backtrace
LSP: INFO kak-lsp server starting (PID=27475). To control log verbosity, set the 'lsp_debug' option
```

With both LSP's autocompletion does not work.

Both LSPs also throw this exception when trying to validate the file, maybe because the setting `css.lint.validProperties` hasn't been set yet, the `settings` are send later from kak-lsp. Both LSP's validation does not work at all with kak-lsp, no errors are reported.

```text
LSP: DEBG From server vscode-html-language-server: {"jsonrpc":"2.0","id":2,"result":null}
LSP: DEBG From server vscode-html-language-server: {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"Unable to load library jquery at /opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/lib/lib/jquery.d.ts"}}
LSP: DEBG From server vscode-html-language-server: {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"Unable to load library lib.es2020.full.d.ts at /opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/node_modules/typescript/lib/lib.es2020.full.d.ts"}}
LSP: DEBG To editor `25726`: evaluate-commands -verbatim -try-client 'client0' lsp-show-message-log vscode-html-language-server 'Unable to load library jquery at /opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/lib/lib/jquery.d.ts'
LSP: log from vscode-html-language-server: Unable to load library jquery at /opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/lib/lib/jquery.d.ts
LSP: DEBG From server vscode-html-language-server: {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":1,"message":"Error while validating file:///Users/roland/Documents/code/pages/html/index.html: Cannot read properties of null (reading 'validProperties')\nTypeError: Cannot read properties of null (reading 'validProperties')\n    at LintConfigurationSettings.getSetting (/opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/node_modules/vscode-css-languageservice/lib/umd/services/lintRules.js:78:29)\n    at new LintVisitor (/opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/node_modules/vscode-css-languageservice/lib/umd/services/lint.js:53:41)\n    at LintVisitor.entries (/opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/node_modules/vscode-css-languageservice/lib/umd/services/lint.js:41:29)\n    at CSSValidation.doValidation (/opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/node_modules/vscode-css-languageservice/lib/umd/services/cssValidation.js:34:60)\n    at _callee$ (/opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/lib/html-language-server/modes/cssMode.js:53:69)\n    at tryCatch (/opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/node_modules/regenerator-runtime/runtime.js:64:40)\n    at Generator.invoke (/opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/node_modules/regenerator-runtime/runtime.js:299:22)\n    at Generator.next (/opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/node_modules/regenerator-runtime/runtime.js:124:21)\n    at asyncGeneratorStep (/opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/lib/html-language-server/modes/cssMode.js:17:103)\n    at _next (/opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/lib/html-language-server/modes/cssMode.js:19:194)"}}
LSP: DEBG To editor `25726`: evaluate-commands -verbatim -try-client 'client0' lsp-show-message-log vscode-html-language-server 'Unable to load library lib.es2020.full.d.ts at /opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/node_modules/typescript/lib/lib.es2020.full.d.ts'
LSP: log from vscode-html-language-server: Unable to load library lib.es2020.full.d.ts at /opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/node_modules/typescript/lib/lib.es2020.full.d.ts
LSP: DEBG From server vscode-html-language-server: {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/roland/Documents/code/pages/html/index.html","diagnostics":[]}}
LSP: DEBG To editor `25726`: evaluate-commands -verbatim -try-client 'client0' lsp-show-message-log vscode-html-language-server 'Error while validating file:///Users/roland/Documents/code/pages/html/index.html: Cannot read properties of null (reading ''validProperties'')
TypeError: Cannot read properties of null (reading ''validProperties'')
    at LintConfigurationSettings.getSetting (/opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/node_modules/vscode-css-languageservice/lib/umd/services/lintRules.js:78:29)
    at new LintVisitor (/opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/node_modules/vscode-css-languageservice/lib/umd/services/lint.js:53:41)
    at LintVisitor.entries (/opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/node_modules/vscode-css-languageservice/lib/umd/services/lint.js:41:29)
    at CSSValidation.doValidation (/opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/node_modules/vscode-css-languageservice/lib/umd/services/cssValidation.js:34:60)
    at _callee$ (/opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/lib/html-language-server/modes/cssMode.js:53:69)
    at tryCatch (/opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke (/opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.next (/opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/node_modules/regenerator-runtime/runtime.js:124:21)
    at asyncGeneratorStep (/opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/lib/html-language-server/modes/cssMode.js:17:103)
    at _next (/opt/homebrew/Cellar/vscode-langservers-extracted/4.10.0/libexec/lib/node_modules/vscode-langservers-extracted/lib/html-language-server/modes/cssMode.js:19:194)'
```

**Comment by krobelus** [comment]
fixed a crash in 2150818c, now looking at others now.

FWIW I 've been told about https://github.com/kristoff-it/superhtml, which we could add to the default config if someone finds it useful.
Helix has it by default, along with vscode-html-language-server, see https://github.com/helix-editor/helix/blob/10c3502a89d51e2d074d0d2ca62f85241d6e8c0f/languages.toml#L99 and
https://github.com/helix-editor/helix/blob/10c3502a89d51e2d074d0d2ca62f85241d6e8c0f/languages.toml#L847

**Comment by krobelus** [comment]
> With both LSP's autocompletion does not work.

works for me with `html-language-server` version 1.95.1.
Typing a single `<` at top level triggers gives me HTML tag name completion.
![image](https://github.com/user-attachments/assets/027fb622-56b4-4c44-9cfa-633cc60df04b)

> Both LSPs also throw this exception when trying to validate the file, 

I've managed to trigger this using your config on the file created by `asciidoctor README.asciidoc > README.html`.
Looking into it..

**Comment by Release-Candidate** [comment]
Btw. I've just tried that again. The first time calling `lsp-formatting` works, the second time calling it kak-lsp craches with the HTML and the CSS LSP. `lsp-formatting-sync` hangs forever, again, on both CSS and HTML.

I guess you should mainly concentrate on the CSS LSP `vscode-css-language-server`, as this is the one throwing the exception in the HTML LSP too (as HTML LSP uses the CSS LSP for inline CSS). 

This CSS file triggers both errors:

```css
body {
	color: black;
}
```

using this minimal configuration:

```text
hook -group lsp-filetype-css global BufSetOption filetype=(?:css|less|scss) %{
    set-option buffer lsp_servers %{
        [vscode-css-language-server]
        root_globs = ["package.json", ".git", ".hg"]
        args = ["--stdio"]
        settings_section = "_"
        [vscode-css-language-server.settings._]
        handledSchemas = ["file"]
	provideFormatter = true
    }
}

```

I personally don't mind the HTML LSP too much, but the CSS one I actually need.
Regarding Helix: CSS works there using the same executable, the JSON LSP is missing all schemas too.

> works for me with `html-language-server` version 1.95.1. 

Yes, for me too now with both before crashing them, I guess that was just some aftermath of the crash.

**Comment by krobelus** [comment]
got a workaround for the validProperties problem. I'll commit it later (or feel free to include it in a PR)

<details>

```patch
From 25205e4434df70556602e99ad1627a73bb622a8c Mon Sep 17 00:00:00 2001
From: Johannes Altmanninger <aclopte@gmail.com>
Date: Mon, 11 Nov 2024 11:00:02 +0100
Subject: [PATCH] Workaround HTML/CSS language server crashing due to missing
 validProperties

LSP has several channels for configuration `initializationOptions`
and `workspace/didChangeConfiguration` we actively send:

	... "initializationOptions":{"css":{"lint":{"validProperties":[]}},"handledSchemas":["file"],"provideFormatter":true}
	LSP: DEBG To server vscode-html-language-server: {"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":{"css":{"lint":{"validProperties":[]}},"handledSchemas":["file"],"provideFormatter":true}}}

but it looks like `vscode-html-language-server` (unlike `tsserver`)
uses `workspace/configuration` (which is requested by the server):

	LSP: DEBG From server vscode-html-language-server: {
	  "jsonrpc": "2.0",
	  "id": 0,
	  "method": "workspace/configuration",
	  "params": {
	    "items": [
	      {
	        "scopeUri": "file:///home/johannes/git/kakoune-lsp/README.html",
	        "section": "css"
	      },
	      {
	        "scopeUri": "file:///home/johannes/git/kakoune-lsp/README.html",
	        "section": "html"
	      },
	      {
	        "scopeUri": "file:///home/johannes/git/kakoune-lsp/README.html",
	        "section": "javascript"
	      },
	      {
	        "scopeUri": "file:///home/johannes/git/kakoune-lsp/README.html",
	        "section": "js/ts"
	      }
	    ]
	  }
	}

Our response is all zero because our only settings section is
"_" (which should only be the case for servers that do not use
`workspace/configuration`.)

	DEBG To server vscode-html-language-server: {"jsonrpc":"2.0","result":[null,null,null,null],"id":0}

which causes

	LSP: log from vscode-html-language-server: Error while validating file:///home/johannes/git/kakoune-lsp/README.html: Cannot read properties of null reading 'validProperties'

Fixes #798
---
 rc/servers.kak | 10 ++++------
 1 file changed, 4 insertions(+), 6 deletions(-)

diff --git a/rc/servers.kak b/rc/servers.kak
index 902378b5..036132e5 100644
--- a/rc/servers.kak
+++ b/rc/servers.kak
@@ -52,6 +52,8 @@ hook -group lsp-filetype-css global BufSetOption filetype=(?:css|less|scss) %{
         [vscode-css-language-server]
         root_globs = ["package.json", ".git", ".hg"]
         args = ["--stdio"]
+        [vscode-css-language-server.settings]
+        css.validProperties = []
     }
 }
 
@@ -151,12 +153,8 @@ hook -group lsp-filetype-html global BufSetOption filetype=html %{
         [vscode-html-language-server]
         root_globs = ["package.json"]
         args = ["--stdio"]
-        settings_section = "_"
-        [vscode-html-language-server.settings._]
-        handledSchemas = ["file"]
-        provideFormatter = true
-        # quotePreference = "single"
-        # javascript.format.semicolons = "insert"
+        [vscode-html-language-server.settings]
+        css.validProperties = []
     }
 }
 
-- 
2.47.0.245.gfacbe4f633
```

</details>

**Comment by krobelus** [comment]
(side thought stating the obvious; these vscode language servers are not exactly trying hard to be easily usable from other editors. Long-term it may be better to use friendlier ones)

**Comment by Release-Candidate** [comment]
You need to add 

```text
provideFormatter = true
```

to the config (for HTML too).

**Comment by krobelus** [comment]
OIC. A kingdom for reasonable defaults

**Comment by krobelus** [comment]
is `provideFormatter` documented anywhere?

**Comment by Release-Candidate** [comment]
> (side thought stating the obvious; these vscode language servers are not exactly trying hard to be easily usable from other editors. Long-term it may be better to use friendlier ones)

Yes, totally. 

If I have time (I'm at work right now) I'm certainly trying the Zig HTML LSP, I'll just have to get Zig running on RISCV before building that. 

> is `provideFormatter` documented anywhere?

Yes, "somewhere" :) But not in the official one, there is **another** possibility to switch formatting on, for each of CSS/SCSS/LESS : https://code.visualstudio.com/docs/languages/css

**Comment by krobelus** [comment]
FWIW, on this file

```html
<body>
		asdf

asdf
asdf
asdf cursor is here
asdf
sadf
</body>
```

`lsp-formatting` will move the cursor to the end.

We already have workarounds in place for servers that send huge text edits
that replace the whole file instead of just targeting the minimal range
(one line in this example). But it seems broken with HTML language server (probably because it's missing a trailing newline).
I'll try to fix.

**Comment by Release-Candidate** [comment]
> I don't know what's the meaning of `handledSchemas = ["file"]`;

I don't know either and didn't care to test if it is needed or not yet, I've just added it because Sublime Text sets that and it's configuration is the best documented one I have found yesterday: https://github.com/sublimelsp/LSP-css/blob/master/LSP-css.sublime-settings
