### ISSUE TITLE
Crash with `lsp-formatting-sync`

### ISSUE THREAD

**Issue by arrufat** [kakoune-lsp/kakoune-lsp#803]
## How to reproduce

Having Zig and ZLS dev versions, start a session:

```console
RUST_BACKTRACE=1 kak main.zig -n -s debug
```

Set it up with the following commands:
```sh
echo "eval -client client0 set buffer filetype zig" | kak -p debug
echo "eval -client client0 source ~/Projects/kakoune-lsp/rc/lsp.kak" | kak -p debug
echo "eval -client client0 source ~/Projects/kakoune-lsp/rc/servers.kak" | kak -p debug
echo "eval -client client0 set buffer lsp_language_id zig" | kak -p debug
echo "eval -client client0 hook window -group format BufWritePre .* lsp-formatting-sync" | kak -p debug
echo "eval -client client0 lsp-enable" | kak -p debug
```

Back in Kakoune, try to save the file with `:w`
It will get stuck, and if I cancel with <kbd>Ctrl</kbd> + <kbd>c</kbd>, then `kak-lsp` crashes:

```
*** This is the debug buffer, where debug info will be written ***
LSP: INFO kak-lsp server starting (PID=22704). To control log verbosity, set the 'lsp_debug' option
LSP: INFO Starting language server zls as `zls`
LSP: INFO Language server stderr: info  ( main ): Starting ZLS      0.14.0-dev.228+03537405 @ 'zls'
LSP: INFO Language server stderr: info  ( main ): Message Tracing:  false
LSP: INFO Language server stderr: info  ( main ): Log Level:        info
LSP: INFO Language server stderr: info  ( main ): Log File:         /home/adria/.cache/zls/zls.log
LSP: INFO Language server stderr: info  (server): Client Info:      kakoune-lsp-18.0.3-snapshot
LSP: INFO Language server stderr: info  (server): Autofix Mode:     source.fixall
LSP: INFO Language server stderr: info  (server): added Workspace Folder: file:///tmp/afac
LSP: INFO Language server stderr: info  (server): Set config option 'builtin_path' to "/home/adria/.cache/zls/builtin.zig"
LSP: INFO Language server stderr: info  (server): Set config option 'zig_lib_path' to "/usr/lib/zig/lib"
LSP: INFO Language server stderr: info  (server): Set config option 'zig_exe_path' to "/usr/bin/zig"
LSP: INFO Language server stderr: info  (server): Set config option 'build_runner_path' to "/home/adria/.cache/zls/build_runner/7daeecc93e0892651971a0397fa18f3a/build_runner.zig"
LSP: INFO Language server stderr: info  (server): Set config option 'global_cache_path' to "/home/adria/.cache/zls"
LSP: ERRO kak-lsp crashed, please report a bug. Find more details in the *debug* buffer.
panicked at src/controller.rs:137:22:
explicit panic
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
LSP: kak-lsp crashed, please report a bug. Find more details in the *debug* buffer.
panicked at src/controller.rs:137:22:
explicit panic
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
```

**Comment by arrufat** [comment]
Even though I built `kak-lsp` in debug mode, I wasn't getting the backtrace, let me know if I can do something else to help :)

**Comment by krobelus** [comment]
I haven't managed to reproduce this. Is `main.zig` an empty file in an empty directory?

Maybe this crash is due to an incomplete upgrade (kak-lsp in `PATH` must match `rc/lsp.kak`).
Sounds like the crashing `kak-lsp` server was built in release mode.

I added extra logs to the reproduction; if you add `set g lsp_debug true`, that should show enough info in the log now

**Comment by arrufat** [comment]
Other servers don't crash, so maybe it's a ZLS issue?

**Comment by arrufat** [comment]
Sorry, I didn't see those before, this?
```
LSP: ERRO kak-lsp crashed, please report a bug. Find more details in the *debug* buffer.
panicked at src/controller.rs:143:21:
expected quote, backslash or space at offset 2, saw 'd'
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
LSP: kak-lsp crashed, please report a bug. Find more details in the *debug* buffer.
panicked at src/controller.rs:143:21:
expected quote, backslash or space at offset 2, saw 'd'
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
Error: no matches found: 'from'
Error: no matches found: 'editor'

```

**Comment by krobelus** [comment]
Nope, you need to run `set g lsp_debug true` before it crashes to get the full log unfortunately

**Comment by krobelus** [comment]
or equivalently, run `kak-lsp --debug -s debug` in a separate terminal

**Comment by arrufat** [comment]
ah, stupid me, I set it on my kakrc... which I am not loading here:
```console
' '' 'map-end' 'textDocument/didSave' }
LSP: ERRO kak-lsp crashed, please report a bug. Find more details in the *debug* buffer.
panicked at src/controller.rs:143:21:
expected quote, backslash or space at offset 2, saw 'd'
   0: kak_lsp::initialize_logger::{{closure}}
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/main.rs:580:13
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: kak_lsp::controller::read_token
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/controller.rs:143:21
   7: kak_lsp::controller::next_string
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/controller.rs:100:5
   8: <T as kak_lsp::controller::Deserializable>::deserialize
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/controller.rs:251:24
   9: kak_lsp::controller::ParserState::next
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/controller.rs:277:9
  10: kak_lsp::controller::dispatch_fifo_request::sync_trailer
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/controller.rs:399:38
  11: kak_lsp::controller::dispatch_fifo_request
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/controller.rs:565:13
  12: kak_lsp::controller::start::{{closure}}
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/controller.rs:729:28
  13: kak_lsp::thread_worker::Worker<I,O>::spawn::{{closure}}
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/thread_worker.rs:83:66
  14: std::sys::backtrace::__rust_begin_short_backtrace
             at /usr/src/debug/rust/rustc-1.82.0-src/library/std/src/sys/backtrace.rs:154:18
  15: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /usr/src/debug/rust/rustc-1.82.0-src/library/std/src/thread/mod.rs:522:17
  16: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /usr/src/debug/rust/rustc-1.82.0-src/library/core/src/panic/unwind_safe.rs:272:9
  17: std::panicking::try::do_call
             at /usr/src/debug/rust/rustc-1.82.0-src/library/std/src/panicking.rs:554:40
  18: __rust_try
  19: std::panicking::try
             at /usr/src/debug/rust/rustc-1.82.0-src/library/std/src/panicking.rs:518:19
  20: std::panic::catch_unwind
             at /usr/src/debug/rust/rustc-1.82.0-src/library/std/src/panic.rs:345:14
  21: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /usr/src/debug/rust/rustc-1.82.0-src/library/std/src/thread/mod.rs:521:30
  22: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /usr/src/debug/rust/rustc-1.82.0-src/library/core/src/ops/function.rs:250:5
  23: std::sys::pal::unix::thread::Thread::new::thread_start
  24: <unknown>
  25: <unknown>
LSP: kak-lsp crashed, please report a bug. Find more details in the *debug* buffer.
panicked at src/controller.rs:143:21:
expected quote, backslash or space at offset 2, saw 'd'
   0: kak_lsp::initialize_logger::{{closure}}
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/main.rs:580:13
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: kak_lsp::controller::read_token
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/controller.rs:143:21
   7: kak_lsp::controller::next_string
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/controller.rs:100:5
   8: <T as kak_lsp::controller::Deserializable>::deserialize
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/controller.rs:251:24
   9: kak_lsp::controller::ParserState::next
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/controller.rs:277:9
  10: kak_lsp::controller::dispatch_fifo_request::sync_trailer
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/controller.rs:399:38
  11: kak_lsp::controller::dispatch_fifo_request
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/controller.rs:565:13
  12: kak_lsp::controller::start::{{closure}}
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/controller.rs:729:28
  13: kak_lsp::thread_worker::Worker<I,O>::spawn::{{closure}}
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/thread_worker.rs:83:66
  14: std::sys::backtrace::__rust_begin_short_backtrace
             at /usr/src/debug/rust/rustc-1.82.0-src/library/std/src/sys/backtrace.rs:154:18
  15: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /usr/src/debug/rust/rustc-1.82.0-src/library/std/src/thread/mod.rs:522:17
  16: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /usr/src/debug/rust/rustc-1.82.0-src/library/core/src/panic/unwind_safe.rs:272:9
  17: std::panicking::try::do_call
             at /usr/src/debug/rust/rustc-1.82.0-src/library/std/src/panicking.rs:554:40
  18: __rust_try
  19: std::panicking::try
             at /usr/src/debug/rust/rustc-1.82.0-src/library/std/src/panicking.rs:518:19
  20: std::panic::catch_unwind
             at /usr/src/debug/rust/rustc-1.82.0-src/library/std/src/panic.rs:345:14
  21: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /usr/src/debug/rust/rustc-1.82.0-src/library/std/src/thread/mod.rs:521:30
  22: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /usr/src/debug/rust/rustc-1.82.0-src/library/core/src/ops/function.rs:250:5
  23: std::sys::pal::unix::thread::Thread::new::thread_start
  24: <unknown>
  25: <unknown>
```

**Comment by krobelus** [comment]
The last `From editor (raw):` line might be helpful, or even the full log

**Comment by krobelus** [comment]
but given that the stacktrace is in the sync-trailer, this sounds like a problem here

```
define-command -hidden lsp-do-send-sync %{
    unset-option buffer lsp_do_send_maybe_async
    evaluate-commands %sh{
        printf >${kak_opt_lsp_fifo} "%s '\''%s'\'' '\''%s'\'' " \
            "${kak_quoted_reg_a}" "${kak_command_fifo}" "${kak_response_fifo}"
        cat ${kak_response_fifo}
    }
}
```

Maybe your shell's printf has some different behavior? Maybe add `set -x` or `| tee /dev/stderr` here

**Comment by krobelus** [comment]
oh my bad, I see the problem. There is bad quoting leftover from when this was wrapped in single quotes.

**Comment by krobelus** [comment]
LMK if it's not fixed

**Comment by arrufat** [comment]
It's fixed, thank you so much!
