### ISSUE TITLE
Crash with duplicated functions in Zig

### ISSUE THREAD

**Issue by arrufat** [kakoune-lsp/kakoune-lsp#811]
## How to reproduce

Having the latest kak-lsp and Zig and ZLS dev versions, start a session:

```console
RUST_BACKTRACE=1 kak main.zig -n -s debug
```

Set it up with the following commands:
```sh
echo "eval -client client0 set buffer filetype zig" | kak -p debug
echo "eval -client client0 source ~/Projects/kakoune-lsp/rc/lsp.kak" | kak -p debug
echo "eval -client client0 source ~/Projects/kakoune-lsp/rc/servers.kak" | kak -p debug
echo "eval -client client0 set buffer lsp_language_id zig" | kak -p debug
echo "eval -client client0 hook window -group format BufWritePre .* lsp-formatting-sync" | kak -p debug
echo "eval -client client0 lsp-enable" | kak -p debug
```

Back in Kakoune, add the following two lines:

```zig
pub fn main() void {}
pub fn main() void {}
```

It will crash with the following stack trace:

```console
*** This is the debug buffer, where debug info will be written ***
LSP: INFO kak-lsp server starting (PID=12075). To control log verbosity, set the 'lsp_debug' option
LSP: INFO Starting language server zls as `zls`
LSP: INFO Language server stderr: info  ( main ): Starting ZLS      0.14.0-dev.233+2eb3a2f5 @ 'zls'
LSP: INFO Language server stderr: info  ( main ): Message Tracing:  false
LSP: INFO Language server stderr: info  ( main ): Log Level:        info
LSP: INFO Language server stderr: info  ( main ): Log File:         /home/adria/.cache/zls/zls.log
LSP: INFO Language server stderr: info  (server): Client Info:      kakoune-lsp-18.1.0-snapshot
LSP: INFO Language server stderr: info  (server): Autofix Mode:     source.fixall
LSP: INFO Language server stderr: info  (server): added Workspace Folder: file:///tmp/afac
LSP: INFO Language server stderr: info  (server): Set config option 'builtin_path' to "/home/adria/.cache/zls/builtin.zig"
LSP: INFO Language server stderr: info  (server): Set config option 'zig_lib_path' to "/usr/lib/zig/lib"
LSP: INFO Language server stderr: info  (server): Set config option 'zig_exe_path' to "/usr/bin/zig"
LSP: INFO Language server stderr: info  (server): Set config option 'global_cache_path' to "/home/adria/.cache/zls"
LSP: INFO Language server stderr: info  (server): Set config option 'build_runner_path' to "/home/adria/.cache/zls/build_runner/7daeecc93e0892651971a0397fa18f3a/build_runner.zig"
LSP: ERRO kak-lsp crashed, please report a bug. Find more details in the *debug* buffer.
panicked at src/diagnostics.rs:14:59:
Failed to parse params: Error { code: InvalidParams, message: "Invalid params: invalid value: string \"/\", expected relative URL without a base.", data: None }
   0: kak_lsp::initialize_logger::{{closure}}
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/main.rs:606:13
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: core::result::Result<T,E>::expect
             at /usr/src/debug/rust/rustc-1.82.0-src/library/core/src/result.rs:1059:23
   8: kak_lsp::diagnostics::publish_diagnostics
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/diagnostics.rs:14:44
   9: kak_lsp::controller::dispatch_server_notification
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/controller.rs:1998:13
  10: kak_lsp::controller::start
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/controller.rs:898:29
  11: kak_lsp::run_main
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/main.rs:458:16
  12: kak_lsp::main
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/main.rs:81:29
  13: core::ops::function::FnOnce::call_once
             at /usr/src/debug/rust/rustc-1.82.0-src/library/core/src/ops/function.rs:250:5
  14: std::sys::backtrace::__rust_begin_short_backtrace
             at /usr/src/debug/rust/rustc-1.82.0-src/library/std/src/sys/backtrace.rs:154:18
  15: std::rt::lang_start::{{closure}}
             at /usr/src/debug/rust/rustc-1.82.0-src/library/std/src/rt.rs:164:18
  16: std::rt::lang_start_internal
  17: std::rt::lang_start
             at /usr/src/debug/rust/rustc-1.82.0-src/library/std/src/rt.rs:163:17
  18: main
  19: <unknown>
  20: __libc_start_main
  21: _start
LSP: kak-lsp crashed, please report a bug. Find more details in the *debug* buffer.
```

**Comment by krobelus** [comment]
Thanks for reporting.
I haven't yet installed zig-git/zls-git (it seems zls-git requires LLVM 19).

This seems like a bug in the development version of zls, because an empty string is not a valid URL.
It seems to be sending that as part of `publishDiagnostics`; a `lsp_debug=true` log will show the full notification.

I think we should fix it to show an error (using `lsp-show-error`).
This will still show it in Clippy which may be annoying but we should really be getting rid of those bugs anyway.

There are a lot these cases where we crash when a language server sends an invalid response.
We should go through them one of these days and change them to `lsp-show-error`.

FWIW a simpler way to reproduce might be

	HOME=$(mktemp -d) kak main.zig -e 'eval %sh{kak-lsp}; set global lsp_debug true; lsp-enable'

Also I'll push a commit that removes the need to set `lsp_language_id` manually with your approach.

**Comment by arrufat** [comment]
Thanks for the quick reply, here's some more context:

```console
LSP: DEBG Buffer contents from editor: {pub fn main() void{}
pub fn main() void{}

}
LSP: DEBG From editor: {{debug} {client0} {true} {false} {/tmp/afac/main.zig} {25} {zig} {zig} {
        [zls]
        root_globs = ["build.zig"]
    } {
    [
        {face="documentation", token="comment", modifiers=["documentation"]},
        {face="comment", token="comment"},
        {face="function", token="function"},
        {face="function", token="method"},
        {face="keyword", token="keyword"},
        {face="module", token="namespace"},
        {face="operator", token="operator"},
        {face="string", token="string"},
        {face="type", token="type"},
        {face="default+d", token="variable", modifiers=["readonly"]},
        {face="default+d", token="variable", modifiers=["constant"]},
        {face="variable", token="variable"},
    ]
} {} {map-end} {textDocument/didChange} {stop}}
LSP: DEBG Received editor request via fifo
LSP: DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_ZIG
LSP: DEBG From editor: {{debug} {client0} {true} {false} {/tmp/afac/main.zig} {25} {zig} {zig} {
        [zls]
        root_globs = ["build.zig"]
    } {
    [
        {face="documentation", token="comment", modifiers=["documentation"]},
        {face="comment", token="comment"},
        {face="function", token="function"},
        {face="function", token="method"},
        {face="keyword", token="keyword"},
        {face="module", token="namespace"},
        {face="operator", token="operator"},
        {face="string", token="string"},
        {face="type", token="type"},
        {face="default+d", token="variable", modifiers=["readonly"]},
        {face="default+d", token="variable", modifiers=["constant"]},
        {face="variable", token="variable"},
    ]
} {} {map-end} {textDocument/codeLens}}
LSP: DEBG To server zls: {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"text":"pub fn main() void{}\npub fn main() void{}\n\n"}],"textDocument":{"uri":"file:///tmp/afac/main.zig","version":25}}}
LSP: DEBG Received editor request via fifo
LSP: DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_ZIG
LSP: DEBG Received editor request via fifo
LSP: DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_ZIG
LSP: DEBG From editor: {{debug} {client0} {true} {false} {/tmp/afac/main.zig} {25} {zig} {zig} {
        [zls]
        root_globs = ["build.zig"]
    } {
    [
        {face="documentation", token="comment", modifiers=["documentation"]},
        {face="comment", token="comment"},
        {face="function", token="function"},
        {face="function", token="method"},
        {face="keyword", token="keyword"},
        {face="module", token="namespace"},
        {face="operator", token="operator"},
        {face="string", token="string"},
        {face="type", token="type"},
        {face="default+d", token="variable", modifiers=["readonly"]},
        {face="default+d", token="variable", modifiers=["constant"]},
        {face="variable", token="variable"},
    ]
} {} {map-end} {textDocument/codeAction} {2.1,2.21} {0} {false} {false} {only}}
LSP: DEBG To server zls: {"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[],"triggerKind":2},"range":{"end":{"character":20,"line":1},"start":{"character":0,"line":1}},"textDocument":{"uri":"file:///tmp/afac/main.zig"}},"id":68}
LSP: DEBG From editor: {{debug} {client0} {true} {false} {/tmp/afac/main.zig} {25} {zig} {zig} {
        [zls]
        root_globs = ["build.zig"]
    } {
    [
        {face="documentation", token="comment", modifiers=["documentation"]},
        {face="comment", token="comment"},
        {face="function", token="function"},
        {face="function", token="method"},
        {face="keyword", token="keyword"},
        {face="module", token="namespace"},
        {face="operator", token="operator"},
        {face="string", token="string"},
        {face="type", token="type"},
        {face="default+d", token="variable", modifiers=["readonly"]},
        {face="default+d", token="variable", modifiers=["constant"]},
        {face="variable", token="variable"},
    ]
} {} {map-end} {kakoune/breadcrumbs} {2}}
LSP: DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_ZIG
LSP: DEBG Received editor request via fifo
LSP: DEBG To server zls: {"jsonrpc":"2.0","method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///tmp/afac/main.zig"}},"id":69}
LSP: DEBG From server zls: {"jsonrpc":"2.0","id":69,"result":[{"name":"main","detail":"fn main() void","kind":12,"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":20}},"selectionRange":{"start":{"line":0,"character":7},"end":{"line":0,"character":11}},"children":[]},{"name":"main","detail":"fn main() void","kind":12,"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":20}},"selectionRange":{"start":{"line":1,"character":7},"end":{"line":1,"character":11}},"children":[]}]}
LSP: DEBG To editor `debug`: evaluate-commands -client client0 -verbatim -- evaluate-commands -draft -client client0 -- 'buffer ''/tmp/afac/main.zig''; try ''set-option window lsp_modeline_breadcrumbs ''''main '''''''
LSP: DEBG From server zls: {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///tmp/afac/main.zig","diagnostics":[{"range":{"start":{"line":0,"character":7},"end":{"line":0,"character":11}},"severity":1,"code":"ast-check","source":"zls","message":"duplicate struct member name 'main'","relatedInformation":[{"location":{"uri":"/","range":{"start":{"line":1,"character":7},"end":{"line":1,"character":11}}},"message":"duplicate name here"},{"location":{"uri":"/","range":{"start":{"line":0,"character":0},"end":{"line":0,"character":3}}},"message":"struct declared here"}]}]}}
LSP: DEBG From server zls: {"jsonrpc":"2.0","id":68,"result":[{"title":"organize @import","kind":"source.organizeImports","isPreferred":true,"edit":{"changes":{"file:///tmp/afac/main.zig":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"newText":"\n"}]}}}]}
LSP: ERRO kak-lsp crashed, please report a bug. Find more details in the *debug* buffer.
panicked at src/diagnostics.rs:14:59:
Failed to parse params: Error { code: InvalidParams, message: "Invalid params: invalid value: string \"/\", expected relative URL without a base.", data: None }
   0: kak_lsp::initialize_logger::{{closure}}
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/main.rs:606:13
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: core::result::Result<T,E>::expect
             at /usr/src/debug/rust/rustc-1.82.0-src/library/core/src/result.rs:1059:23
   8: kak_lsp::diagnostics::publish_diagnostics
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/diagnostics.rs:14:44
   9: kak_lsp::controller::dispatch_server_notification
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/controller.rs:1998:13
  10: kak_lsp::controller::start
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/controller.rs:898:29
  11: kak_lsp::run_main
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/main.rs:458:16
  12: kak_lsp::main
             at /home/adria/.cache/yay/kakoune-lsp-git/src/kakoune-lsp-git/src/main.rs:81:29
  13: core::ops::function::FnOnce::call_once
             at /usr/src/debug/rust/rustc-1.82.0-src/library/core/src/ops/function.rs:250:5
  14: std::sys::backtrace::__rust_begin_short_backtrace
             at /usr/src/debug/rust/rustc-1.82.0-src/library/std/src/sys/backtrace.rs:154:18
  15: std::rt::lang_start::{{closure}}
             at /usr/src/debug/rust/rustc-1.82.0-src/library/std/src/rt.rs:164:18
  16: std::rt::lang_start_internal
  17: std::rt::lang_start
             at /usr/src/debug/rust/rustc-1.82.0-src/library/std/src/rt.rs:163:17
  18: main
  19: <unknown>
  20: __libc_start_main
  21: _start
```

I really should get more familiar with how all this stuff works, so I could help a bit more.

Do you think I need to report a bug to ZLS?

**Comment by krobelus** [comment]
I've reported it as https://github.com/zigtools/zls/issues/2095, hopefully that's enough information, feel free to add

**Comment by krobelus** [comment]
got the panic report, thanks. Made me realize that distro packages run `strip target/release/kak-lsp`, which means we can't get file/line information from the addresses in stack traces. (At least we get innermost location like `panicked at src/controller.rs:794:26:`.)
Maybe we can upload debug information files to Sentry, will see

**Comment by arrufat** [comment]
Fixed upstream, thanks!

**Comment by krobelus** [comment]
Nice. We should probably still make it a real error but I'd probably want to apply it across the whole code base in one go
