### ISSUE TITLE
Crash with clangd

### ISSUE THREAD

**Issue by SRAZKVT** [kakoune-lsp/kakoune-lsp#816]
Hi, i tried to update my config to 18.1.0, as my setup was still using 17.1.2, just to see that whenever i try a c file, kak-lsp tries a few times but always crashes at the same place

<details>
<summary>Log</summary>

```
*** This is the debug buffer, where debug info will be written ***
LSP: INFO kak-lsp server starting (PID=13237). To control log verbosity, set the 'lsp_debug' option
LSP: DEBG From editor (raw): {'13217' '' 'false' 'true' '' '0' '' '' '' '
    [
        {face="documentation", token="comment", modifiers=["documentation"]},
        {face="comment", token="comment"},
        {face="function", token="function"},
        {face="function", token="method"},
        {face="keyword", token="keyword"},
        {face="module", token="namespace"},
        {face="operator", token="operator"},
        {face="string", token="string"},
        {face="type", token="type"},
        {face="default+d", token="variable", modifiers=["readonly"]},
        {face="default+d", token="variable", modifiers=["constant"]},
        {face="variable", token="variable"},
    ]
' '' 'map-end' 'workspace/didChangeConfiguration' '' 'map-end'}
LSP: DEBG From editor: {{13217} {} {false} {true} {} {0} {} {} {} {
    [
        {face="documentation", token="comment", modifiers=["documentation"]},
        {face="comment", token="comment"},
        {face="function", token="function"},
        {face="function", token="method"},
        {face="keyword", token="keyword"},
        {face="module", token="namespace"},
        {face="operator", token="operator"},
        {face="string", token="string"},
        {face="type", token="type"},
        {face="default+d", token="variable", modifiers=["readonly"]},
        {face="default+d", token="variable", modifiers=["constant"]},
        {face="variable", token="variable"},
    ]
} {} {map-end} {workspace/didChangeConfiguration} {} {map-end}}
LSP: DEBG From editor (raw): {'13217' '' 'true' 'false' '/home/sarah/test.c' '1' 'c' 'c_cpp' '
        [clangd]
        args = ["--log=error"]
        root_globs = ["compile_commands.json", ".clangd", ".git", ".hg"]
    ' '
    [
        {face="documentation", token="comment", modifiers=["documentation"]},
        {face="comment", token="comment"},
        {face="function", token="function"},
        {face="function", token="method"},
        {face="keyword", token="keyword"},
        {face="module", token="namespace"},
        {face="operator", token="operator"},
        {face="string", token="string"},
        {face="type", token="type"},
        {face="default+d", token="variable", modifiers=["readonly"]},
        {face="default+d", token="variable", modifiers=["constant"]},
        {face="variable", token="variable"},
    ]
' '' 'map-end' 'textDocument/didOpen'}
LSP: DEBG From editor (raw): { }
LSP: DEBG Received editor request via fifo
LSP: DEBG Unsupported scratch buffer, ignoring request from buffer ''
LSP: DEBG Failed to route workspace/didChangeConfiguration
LSP: DEBG To editor `13217`: nop
LSP: DEBG From editor: {{13217} {} {true} {false} {/home/sarah/test.c} {1} {c} {c_cpp} {
        [clangd]
        args = ["--log=error"]
        root_globs = ["compile_commands.json", ".clangd", ".git", ".hg"]
    } {
    [
        {face="documentation", token="comment", modifiers=["documentation"]},
        {face="comment", token="comment"},
        {face="function", token="function"},
        {face="function", token="method"},
        {face="keyword", token="keyword"},
        {face="module", token="namespace"},
        {face="operator", token="operator"},
        {face="string", token="string"},
        {face="type", token="type"},
        {face="default+d", token="variable", modifiers=["readonly"]},
        {face="default+d", token="variable", modifiers=["constant"]},
        {face="variable", token="variable"},
    ]
} {} {map-end} {textDocument/didOpen} {stop}}
LSP: DEBG From editor (raw): { 'stop' '13217' '' 'true' 'false' '/home/sarah/test.c' '1' 'c' 'c_cpp' '
        [clangd]
        args = ["--log=error"]
        root_globs = ["compile_commands.json", ".clangd", ".git", ".hg"]
    ' '
    [
        {face="documentation", token="comment", modifiers=["documentation"]},
        {face="comment", token="comment"},
        {face="function", token="function"},
        {face="function", token="method"},
        {face="keyword", token="keyword"},
        {face="module", token="namespace"},
        {face="operator", token="operator"},
        {face="string", token="string"},
        {face="type", token="type"},
        {face="default+d", token="variable", modifiers=["readonly"]},
        {face="default+d", token="variable", modifiers=["constant"]},
        {face="variable", token="variable"},
    ]
' '' 'map-end' 'textDocument/codeLens' }
LSP: DEBG Buffer contents from editor: {#include <stdio.h>

int main(void) {
	printf("Hello, World!\n");
	return 0;
}
}
LSP: DEBG Received editor request via fifo
LSP: DEBG From editor: {{13217} {} {true} {false} {/home/sarah/test.c} {1} {c} {c_cpp} {
        [clangd]
        args = ["--log=error"]
        root_globs = ["compile_commands.json", ".clangd", ".git", ".hg"]
    } {
    [
        {face="documentation", token="comment", modifiers=["documentation"]},
        {face="comment", token="comment"},
        {face="function", token="function"},
        {face="function", token="method"},
        {face="keyword", token="keyword"},
        {face="module", token="namespace"},
        {face="operator", token="operator"},
        {face="string", token="string"},
        {face="type", token="type"},
        {face="default+d", token="variable", modifiers=["readonly"]},
        {face="default+d", token="variable", modifiers=["constant"]},
        {face="variable", token="variable"},
    ]
} {} {map-end} {textDocument/codeLens}}
LSP: ERRO kak-lsp crashed, please report a bug. Find more details in the *debug* buffer.
panicked at src/controller.rs:1293:18:
called `Option::unwrap()` on a `None` value
disabled backtrace
LSP: kak-lsp crashed, please report a bug. Find more details in the *debug* buffer.
panicked at src/controller.rs:1293:18:
called `Option::unwrap()` on a `None` value
disabled backtrace
LSP: INFO kak-lsp server starting (PID=13301). To control log verbosity, set the 'lsp_debug' option
LSP: DEBG From editor (raw): {'13217' 'client0' 'true' 'false' '/home/sarah/test.c' '1' 'c' 'c_cpp' '
        [clangd]
        args = ["--log=error"]
        root_globs = ["compile_commands.json", ".clangd", ".git", ".hg"]
    ' '
    [
        {face="documentation", token="comment", modifiers=["documentation"]},
        {face="comment", token="comment"},
        {face="function", token="function"},
        {face="function", token="method"},
        {face="keyword", token="keyword"},
        {face="module", token="namespace"},
        {face="operator", token="operator"},
        {face="string", token="string"},
        {face="type", token="type"},
        {face="default+d", token="variable", modifiers=["readonly"]},
        {face="default+d", token="variable", modifiers=["constant"]},
        {face="variable", token="variable"},
    ]
' '' 'map-end' 'textDocument/didChange'}
LSP: DEBG From editor (raw): { 'stop' '13217' 'client0' 'true' 'false' '/home/sarah/test.c' '1' 'c' 'c_cpp' '
        [clangd]
        args = ["--log=error"]
        root_globs = ["compile_commands.json", ".clangd", ".git", ".hg"]
    ' '
    [
        {face="documentation", token="comment", modifiers=["documentation"]},
        {face="comment", token="comment"},
        {face="function", token="function"},
        {face="function", token="method"},
        {face="keyword", token="keyword"},
        {face="module", token="namespace"},
        {face="operator", token="operator"},
        {face="string", token="string"},
        {face="type", token="type"},
        {face="default+d", token="variable", modifiers=["readonly"]},
        {face="default+d", token="variable", modifiers=["constant"]},
        {face="variable", token="variable"},
    ]
' '' 'map-end' 'textDocument/codeAction' '1.1,1.1' '0' 'false' 'false' 'only' '13217' 'client0' 'true' 'false' '/home/sarah/test.c' '1' 'c' 'c_cpp' '
        [clangd]
        args = ["--log=error"]
        root_globs = ["compile_commands.json", ".clangd", ".git", ".hg"]
    ' '
    [
        {face="documentation", token="comment", modifiers=["documentation"]},
        {face="comment", token="comment"},
        {face="function", token="function"},
        {face="function", token="method"},
        {face="keyword", token="keyword"},
        {face="module", token="namespace"},
        {face="operator", token="operator"},
        {face="string", token="string"},
        {face="type", token="type"},
        {face="default+d", token="variable", modifiers=["readonly"]},
        {face="default+d", token="variable", modifiers=["constant"]},
        {face="variable", token="variable"},
    ]
' '' 'map-end' 'kakoune/breadcrumbs' '1' }
```

</details>
(Sorry, not in a code block, github doesn't want it to look nice due to backticks in log)

This is the current configuration in ~/.config/kak/kakrc
```
eval %sh{kak-lsp}
set global lsp_debug true
lsp-enable
```

I am using void linux, and the kakoune packaged by void linux, and i tried both void's kak-lsp package, and the binary package from here, and both give the same issue, and both are version 18.1.0.

it's triggered by any c file from my testing, i didn't test c++, but i suppose it also is affected. All other languages i use, or at least, those i have used at least once, are fine (haskell, rust and typst)

**Comment by krobelus** [comment]
can you share (the C++ part of) your `kak-lsp.toml`?

**Comment by SRAZKVT** [comment]
the `kak-lsp.toml` that was used in 17.1.2 but deprecated in 18.X ?

```
[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_commands.json", ".clangd", "Makefile", "build.sh", ".git"]
command = "clangd"
```

it's just the default one but with a few added roots

**Comment by krobelus** [comment]
Thanks, that was an embarassing regression in 18.1.0.
Should have kept around the tests for the old config syntax..

> (Sorry, not in a code block, github doesn't want it to look nice due to backticks in log)

The workaround is to add blank lines around backticks:


````
<details>

```
code block here
```

</details>
````

**Comment by SRAZKVT** [comment]
Thanks for fixing this (and for maintaining kak-lsp)

> > (Sorry, not in a code block, github doesn't want it to look nice due to backticks in log)
> 
> The workaround is to add blank lines around backticks:
> 
> ```
> <details>
> 
> ```
> code block here
> ```
> 
> </details>
> ```

oh, didn't know that, thanks
